### ISSUE TITLE
❓ Does this do the same as Item Model Fix?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [MehVahdJukaar/modelfix-multi#1]
I was wondering if this did the same as Item Model Fix, or does this do something similar? 

https://www.curseforge.com/minecraft/mc-mods/item-model-fix

**Comment by MehVahdJukaar** [comment]
I wrote all you need to know in the mod description. As far as I'm aware that mod does not fix the issue for block models and just focuses on item model as it does not remove texture zooming for all textures

**Comment by Aces-and-Jacks** [comment]
ok thanks
