### ISSUE TITLE
Update to 1.19.3 (Fabric)

### ISSUE THREAD

**Issue by DreamStanMan** [MehVahdJukaar/modelfix-multi#10]
The Model Gap Fix mod does not work on 1.19.3, as it needs to be updated.

**Comment by MehVahdJukaar** [comment]
Chill it literally just came out. 1.19.3 is a major update so don't expect other mods to come out immediately (tho this is trivial so it will soon when I'm free)

**Comment by DreamStanMan** [comment]
I understand, and I was just submitting this issue to let you know that the latest version of the mod has issues with 1.19.3. :)

**Comment by RaptaG** [comment]
> when I'm free

Please let us know!

**Comment by MehVahdJukaar** [comment]
Mod has been updated 3 days ago
