### ISSUE TITLE
Crash with Cosmetica

### ISSUE THREAD

**Issue by emoace** [MehVahdJukaar/modelfix-multi#11]
Hi I was making a pack and noticed that Cosmetica and this mod crash when trying to render the player, it seems. If I remove either one of them, then there are no crashes. 

Here is the crash report:

[crash-2023-01-03_01.21.11-client.txt](https://github.com/MehVahdJukaar/modelfix-multi/files/10334834/crash-2023-01-03_01.21.11-client.txt)

**Comment by MehVahdJukaar** [comment]
No idea. Maybe report to them too. Seems like calling this.atlas() throws an unconditional exception on their model when it shouldn't. I don't think there's much I can do besides add some direct compatibility workaround

**Comment by emoace** [comment]
I checked their github and it seems they are aware of this issue and have fixed it in dev, but they haven't released the fix yet: https://github.com/Cosmetica-cc/Cosmetica/issues/77

**Comment by Julienraptor01** [comment]
They have released the fix and this issue could be closed

**Comment by MehVahdJukaar** [comment]
Nice
