### ISSUE TITLE
Crash at startup reported by a FO user 

### ISSUE THREAD

**Issue by Julienraptor01** [MehVahdJukaar/modelfix-multi#13]
Idk if it's related to #9 but some FO user reported us he crashed at launch
Here are the logs
https://mclo.gs/ayyjhgQ
https://mclo.gs/IZypLil
It's reported on Fabric 1.19.3

**Comment by MehVahdJukaar** [comment]
Seems like they have a broken or badly formatted JSON config file. Deleting should fic
