### ISSUE TITLE
crash on 1.18.2

### ISSUE THREAD

**Issue by Aceplante2** [MehVahdJukaar/modelfix-multi#21]
This has been happening for a while but just posting this in case youre somehow not aware.

Also, why is the 1.18 file "1.8" and the 1.19 file "1.12"

**Comment by MehVahdJukaar** [comment]
Because that's the mod version not MC version. Exains this issue too..

**Comment by Aceplante2** [comment]
To clarify, I am playing on 1.18.2 forge

**Comment by Aceplante2** [comment]
Odd, it did not crash this time when I went in to test it again. But I'll let you know if it happens again.
