### ISSUE TITLE
1.20

### ISSUE THREAD

**Issue by MenacingPerson** [MehVahdJukaar/modelfix-multi#25]
Please add it

(If it already works, then it's not marked as compat on modrinth and should be)

**Comment by SushiLord** [comment]
any news on this ?

**Comment by ItsukaHiro** [comment]
I'm still waiting for 1.20
Although I can force the mod running on 1.20.1, but it seem not actually work (game run fine, but stitching still happen)

**Comment by MenacingPerson** [comment]
I'll close this because it was added
