### ISSUE TITLE
The fix can cause artifacts & Suggestion for liquid support

### ISSUE THREAD

**Issue by Firestrike1** [MehVahdJukaar/modelfix-multi#4]
The mod does nothing. There are still gaps in both modded and vanilla items and blocks.
![2022-09-27_16 09 56](https://user-images.githubusercontent.com/88449275/192486314-7e501aa7-f0d5-4322-ac7a-99029e3017d4.png)
![2022-09-27_16 09 23](https://user-images.githubusercontent.com/88449275/192486345-d8f7ab0d-ae66-407c-b11a-b9353feb281c.png)
![2022-09-27_16 20 18](https://user-images.githubusercontent.com/88449275/192487496-8dd17187-824b-4391-8117-3e568aba71de.png)
![2022-09-27_15 54 39](https://user-images.githubusercontent.com/88449275/192486402-cab21ffc-cf4e-4bb6-a161-883eb4689f02.png)
![2022-09-27_15 51 49](https://user-images.githubusercontent.com/88449275/192486516-00f9915a-a7e4-41ff-a795-aeabe6ca596d.png)
![2022-09-27_15 52 06](https://user-images.githubusercontent.com/88449275/192486529-8a7f428d-182a-48a2-aeb3-fd1726d5dd03.png)
![2022-09-27_16 17 35](https://user-images.githubusercontent.com/88449275/192486845-870ff15e-4594-4288-bf6c-540817bb2d34.png)

**Comment by MehVahdJukaar** [comment]
The mod is working, I can see it from your screenshots that the big gaps in the sides of the models are gone due to texture scaling being removed (check the bug description or look at a door hinge and you'll see). Those tiny ones on corners are an artifact of another tweak I added that tries to cover other very tiny gaps that can still appear due to rounding errors. This seem to vary on your configuration and it's either one or the other. I'll likely add a config so people can tweak that value to the perfect parameter that hides both

**Comment by MehVahdJukaar** [comment]
So mod does nothing for liquids

**Comment by Firestrike1** [comment]
Well, now I feel bad for saying that your mod does nothing. I meant to say that something was disrupting it's work within my modpack, or for example it not working specifically on fabric, rather than claiming that it does nothing from technical side of things (with I know nothing of). But for some reason I didn't bothered to word it correctly, sorry for that.
 Liquids are usually not a big deal, you can barely notice any gaps in vanilla ones. But as you can see on that black liquid from Yttr, it can be quite unpleasant in some cases (especially with high contrast between liquid and what's behind it and while moving). sadly, there are no solutions to this and I thought your mod could fix the issue since you mentioned it's working not just for items.
 Anyway, thanks for your efforts and explanation, I hope your mod will go a long way and succeeds at helping people with this sort of issues

**Comment by RaptaG** [comment]
Is there any progress with this?

**Comment by Firestrike1** [comment]
New release made gaps smaller, but still didn't completely solved the problem
![2022-10-09_16 21 30](https://user-images.githubusercontent.com/88449275/194750297-5a929df4-5a8c-4fdb-8a38-0fd2ba66e92b.png)

**Comment by MehVahdJukaar** [comment]
New release added a config so you can tweak those values to be the exact ones for your system

**Comment by Firestrike1** [comment]
Config appears to be forge-only for now, I use fabric. Besides, I'm not sure if all people will be able to figure out how to use it, or even bother to try, as they would expect most mods to work right out of the box

**Comment by MehVahdJukaar** [comment]
Didn't have time to add on yesterday. It's in th latest update from today

**Comment by MehVahdJukaar** [comment]
To add onto this if you do find better values that work for you please send so I can test and see if I can replace the current one si there won't be tiny gaps for more people

**Comment by MehVahdJukaar** [comment]
Hm maybe i uploaded the wrong file...

**Comment by Firestrike1** [comment]
After installing 1.8 all the gaps are completely gone. Thank you

![2022-10-13_18 50 10](https://user-images.githubusercontent.com/88449275/195589360-932b4d38-9c60-4046-ac0c-576984d427b5.png)
![2022-10-13_18 50 27](https://user-images.githubusercontent.com/88449275/195589376-829db753-187c-46fd-b991-11b05411e6ae.png)
