### ISSUE TITLE
swords and some tools still have gaps

### ISSUE THREAD

**Issue by szunakabeats** [MehVahdJukaar/modelfix-multi#5]
Fabric 1.19.2
Mod version 1.5

![2022-09-28_21 06 34](https://user-images.githubusercontent.com/88375166/192868251-73ea70a1-442f-457f-8d2f-baf9a98f3a2c.png)

**Comment by Firestrike1** [comment]
Duplicate of #4

**Comment by RaptaG** [comment]
Shouldn't this be closed @szunakabeats?

**Comment by szunakabeats** [comment]
oh yea sry it should :) i had to much to do lately. thx for working on it !
