### ISSUE TITLE
1.21.3-1.10 NeoForge unable to enter the game

### ISSUE THREAD

**Issue by 3gf8jv4dv** [MehVahdJukaar/modelfix-multi#50]
The `loaderVersion` field in `neoforge.mods.toml` should be written like this:

```diff
- loaderVersion = "[21.2,)"
+ loaderVersion = "[1,)"
```

![error-screen-neoforge](https://github.com/user-attachments/assets/7bcc4c07-d753-411d-ba75-bafd4a82458b)

**Comment by BugmanBugman** [comment]
Getting this on 1.21.4 too, pls fix
