### ISSUE TITLE
Update source

### ISSUE THREAD

**Issue by Julienraptor01** [MehVahdJukaar/modelfix-multi#8]
The last commit is add fabric configs while the latest version of the mod has a loader split which should reflect in here ?

**Comment by MehVahdJukaar** [comment]
I can't make sense of that question. Could your rephrase?
The mod recent "loader split" just ditched the single cross loader jars as it was causing problems and I sticked to 2 separate jars instead. The mod was created to work on 2 loaders to begin with

**Comment by Julienraptor01** [comment]
OK so actually you mean that it didn't necessitate any code change from going from universal jar to specific loader jar ?

**Comment by MehVahdJukaar** [comment]
No no code changes. I just don't use the merged jar anymore
